my_string =input()
print(len(my_string))
print(my_string.upper())
print(my_string.lower())
print('Hello, user'.replace(' ',''),my_string.replace(' ',''))
print(my_string[0])
print(my_string[-1])